config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/about', to: 'static_pages#about'
  resources :beds
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bed.rb
class Bed < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/beds_controller.rb
class BedsController < ApplicationController
  def index
    @beds = Bed.all
  end

  def show
    @bed = Bed.find(params[:id])
  end

  def new
    @bed = Bed.new
  end

  def edit
    @bed = Bed.find(params[:id])
  end

  def create
    @bed = Bed.new(beds_params)
    if @bed.save
      redirect_to beds_path
    else
      render :new
    end
  end

  def update
    @bed = Bed.find(params[:id])
    if @bed.update(beds_params)
      redirect_to beds_path
    else
      render :edit
    end
  end

  def destroy
    Bed.find(params[:id]).destroy
    redirect_to beds_path
  end

  private

    def beds_params
      params.require(:bed).permit(:title, :manu, :model, :price, :rating)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beds_helper.rb
module BedsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/beds/edit.html.erb
<h1>Edit Bed Details</h1>
<br />
<%= form_for @bed do |f| %>
<%= f.label :title %>
<%= f.text_area :title %>
<%= f.label :manu %>
<%= f.text_area :manu %>
<%= f.label :model %>
<%= f.text_area :model %>
<%= f.label :price %>
<%= f.text_area :price %>
<%= f.label :rating %>
<%= f.text_area :rating %>
<%= f.submit %>
<% end %> 

app/views/beds/index.html.erb
<h1>List of All Beds</h1>
<br />
<p> <% @beds.each do |bed| %>
  <strong>Title:</strong> <%= bed.title %>
  <strong>Manufacturer: </strong><%= bed.manu %>
  <strong>Model: </strong><%= bed.model %>
  <strong>Price: $</strong><%= bed.price %>
  <strong>Customer Rating: </strong><%= bed.rating %>
  <%= link_to 'Show', bed_path(bed) %>
  <%= link_to 'Edit', edit_bed_path(bed) %>
  <%= link_to 'Delete', bed, method: :delete %>
</p>
<% end %>

app/views/beds/new.html.erb
<h1>Create a New Bed</h1>
<br />
<%= form_for @bed do |f| %>
<%= f.label :title %>
<%= f.text_area :title %>
<%= f.label :manu %>
<%= f.text_area :manu %>
<%= f.label :model %>
<%= f.text_area :model %>
<%= f.label :price %>
<%= f.text_area :price %>
<%= f.label :rating %>
<%= f.text_area :rating %>
<%= f.submit %>
<% end %> 

app/views/beds/show.html.erb
<h1>Details of Selection</h1>
<%= @bed.title %>
<%= @bed.manu %>
<%= @bed.model %>
<%= @bed.price %>
<%= @bed.rating %>

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', root_path %>
<%= link_to 'About', about_path %>
<%= link_to 'Beds', beds_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBeds</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', "https://fonts.googleapis.com/css?family=Gaegu" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/static_pages/about.html.erb
<h1>About Me</h1>
<p>I was born in a cross-fire hurricane</<p>
<p>And I howled at the morning driving rain</<p>
<p>But it's all right now, in fact, it's a gas</<p>
<p>But it's all right. I'm Jumpin' Jack Flash</<p>
<p><i>It's a gas, gas, gas</i></<p>
<p>I was raised by a toothless, bearded hag,</<p>
<p>I was schooled with a strap right across my back</<p>
<p>But it's all right now, in fact, it's a gas</<p>
<p>But it's all right, I'm Jumpin' Jack Flash</<p>
<p><i>It's a gas, gas, gas</i></<p>
<p>I was drowned, I was washed up and left for dead</<p>
<p>I fell down to my feet and I saw they bled , yeah yeah</<p>
<p>I frowned at the crumbs of a crust of bread</<p>
<p><i>Yeah, yeah, yeah</i></<p>
<p>I was crowned with a spike right through my head</<p>
<p>But it's all right now, in fact, it's a gas</<p>
<p>But it's all right, I'm Jumpin' Jack Flash</<p>
<p><i>It's a gas, gas, gas</<p>
<p>Jumping Jack Flash, its a gas</<p>
<p>Jumping Jack Flash, its a gas</<p>
<p>Jumping Jack Flash, its a gas</<p>
<p>Jumping Jack Flash, its a gas</<p>
<p>Jumping Jack Flash, its a gas</<p>
<p>Jumping Jack Flash, its a gas</i></<p>

app/views/static_pages/home.html.erb
<h1>Welcome to the Beds Rails App</h1>
<p>Here you can look at beds records, as well as do stuff with bed records.</p>
<p>Hold on to your ass.</p>